language: ruby
cache: bundler
bundler_args: --jobs=3 --retry=3 --deployment --without production
before_script:
  - bundle exec rake db:seed
env:
  global:
  - DATABASE_URL=/tmp/test.db
rvm:
  - 2.1.5
